### PR TITLE
mkdirp resolved value is an error only when in memory mode

### LINKED ISSUE #251: Could not create output folder error
**Describe the bug**
This error appears to me from version 5.0.2 and up. 5.0.1 and down works fine.
ERROR in [AssetsWebpackPlugin] Could not create output folder /home/user/git/myApp/frontend/target/build_assets

The target folder is wiped before install, but the plugin successfully creates the target- and build_assets-folders. Also the webpack-assets.json file is successfully created, with sensible content.
So the plugin seems to do what it's supposed to do, yet it produces an error.

**Webpack Config**
My AssetsPlugin is set up like this.
```
            new AssetsPlugin({
                fullPath: false,
                path: path.join(__dirname, 'target', 'build_assets'),
            }),
```

What other parts of the config would be useful to know? Given the fact that folders and assets file are created where they are supposed to be, I have a feeling the configuration isn't the problem.

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server 7.8
 - Node version: 12.18.3
 - Plugin version: 5.0.2 (also tried 5.0.3)

### PR DESCRIPTION
**Pull request by henrikhermansen**
This changes the way we handle the Promise from `mkdirp` when it resolves with a value.
A resolved value should only be treated as an error in memory mode.

Further explanations can be found in the issue.

**Test plan (required)**

I have altered the test `doesn't include full publicPath` to verify the changes. Without the changes to `createOutputWriter.js` this test would now fail.

This also required me to make some changes to `expectOutput.js`. This file used to manually create the output directory, which meant we didn't actually test if `mkdip` was used correctly in `createOutputWriter.js`.

**Closing issues**

closes #251

### CODE REVIEW

File: test/utils/expectOutput.js [hunk 1]
```diff
@@ -20,37 +19,29 @@ module.exports = function (outputDir) {
     }
 
     const webpackConfig = args.config
+    if (webpackConfig.plugins && webpackConfig.plugins[0].options.path) {
+      outputDir = path.join(__dirname, `../../${webpackConfig.plugins[0].options.path}`)
+    }
```
Comment (henrikhermansen) [inline test/utils/expectOutput.js:24]: I'm not very happy about this `if` block. Neither the condition nor the way I update the `outputDir`.
It works, but I feel like it's a bit hacky and might break if more elaborate tests are added at some point.

I would love some suggestion on how to make this work more like it actually does inside webpack and the Plugin.

Comment (ztoben) [reply test/utils/expectOutput.js:24]: @henrikhermansen, I think this is a good start. I can certainly think about this more later and make it less brittle if necessary.

**Comment by ztoben** [comment]
LGTM 👍
